/**
 * The press stills: real frames of this game, addressable from the app.
 *
 * GENERATED by `tools/make-brand.mjs` in the same pass that encodes the files, so this list
 * can never name a plate `public/press/` does not hold. Do not edit by hand —
 * `node tools/qa-brand.mjs` re-derives it and fails on drift.
 *
 * `public/press/manifest.json` is the same set with everything else about it: which battle,
 * where the camera stood, every rendition's bytes, and the luminance measurements these
 * `scrimForGold` values are the summary of.
 *
 * Intended uses, in the order they matter:
 *
 *   1. **The instant first paint.** A live scene has to boot the renderer; a still is on
 *      screen in milliseconds. `HERO` is the one to show, and `src`/`srcset` are sized so a
 *      phone does not fetch a desktop plate.
 *   2. **The fallback** for anything that cannot afford a live scene — a weak GPU, a small
 *      viewport, a device already told it is too narrow to play on.
 *   3. **The link preview**, which is `/og/total-claude.jpg`, cropped from `HERO`.
 *
 * `scrimForGold` is the smallest black scrim alpha at which `--gold` (#d9b25f) type clears
 * 4.5:1 against the brightest part of the region a centred menu sheet covers. 0 means none is
 * needed. It is measured on every frame rather than eyeballed on one.
 */

export interface PressPlate {
  /** The `press-*` shot in `tools/shoot.mjs` that produced it. */
  id: string;
  hero: boolean;
  /** For a screen reader, and for `og:image:alt` on the hero. */
  alt: string;
  /** Every rendition, for a `srcset` attribute. Widths: 960, 1440. */
  srcset: string;
  /** The middle rendition, for a plain `src` fallback. */
  src: string;
  width: number;
  height: number;
  /** Smallest black scrim alpha at which gold type clears 4.5:1 on this frame. */
  scrimForGold: number;
}

export const PRESS_PLATES: readonly PressPlate[] = [
  {
    id: "press-rome-line",
    hero: true,
    alt: "Legionary cohorts drawn up in packed ranks at first light, painted shields and helmets catching the low sun, a vexillum among them.",
    srcset: "/press/press-rome-line-960.webp 960w, /press/press-rome-line-1440.webp 1440w, /press/press-rome-line-1920.webp 1920w",
    src: "/press/press-rome-line-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.5,
  },
  {
    id: "press-carth-elephants",
    hero: false,
    alt: "A Carthaginian elephant line advancing in front of the Punic centre in late afternoon light, crews in the towers on their backs.",
    srcset: "/press/press-carth-elephants-960.webp 960w, /press/press-carth-elephants-1440.webp 1440w",
    src: "/press/press-carth-elephants-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.4,
  },
  {
    id: "press-pydna-clash",
    hero: false,
    alt: "Thousands of men locked together on open Macedonian ground at Pydna, 168 BC, spears and standards above the press.",
    srcset: "/press/press-pydna-clash-960.webp 960w, /press/press-pydna-clash-1440.webp 1440w",
    src: "/press/press-pydna-clash-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.65,
  },
  {
    id: "press-rome-melee",
    hero: false,
    alt: "Inside the melee on the Campus Martius in late light: legionaries and Juthungi warriors at arm's length, spears crossed above them.",
    srcset: "/press/press-rome-melee-960.webp 960w, /press/press-rome-melee-1440.webp 1440w",
    src: "/press/press-rome-melee-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0,
  },
  {
    id: "press-rome-host",
    hero: false,
    alt: "A Juthungi warband coming on at eye level, painted round shields, no two men kitted the same.",
    srcset: "/press/press-rome-host-960.webp 960w, /press/press-rome-host-1440.webp 1440w",
    src: "/press/press-rome-host-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.65,
  },
  {
    id: "press-rome-wall",
    hero: false,
    alt: "The Aurelian Wall of Rome at mid-morning, its towers and gatehouse above the glacis, the city behind it.",
    srcset: "/press/press-rome-wall-960.webp 960w, /press/press-rome-wall-1440.webp 1440w",
    src: "/press/press-rome-wall-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.65,
  },
  {
    id: "press-carth-wall",
    hero: false,
    alt: "The wall of Carthage from the field in late afternoon, Roman assault columns drawn up on the plain before it.",
    srcset: "/press/press-carth-wall-960.webp 960w, /press/press-carth-wall-1440.webp 1440w",
    src: "/press/press-carth-wall-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.4,
  },
  {
    id: "press-rome-cavalry",
    hero: false,
    alt: "A wedge of Roman equites sweeping the flank at eye level in low sun.",
    srcset: "/press/press-rome-cavalry-960.webp 960w, /press/press-rome-cavalry-1440.webp 1440w",
    src: "/press/press-rome-cavalry-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0,
  },
  {
    id: "press-rome-city",
    hero: false,
    alt: "Rome from above at first light: the Aurelian circuit along the crest, the Tiber below it, the fabric of the city inside.",
    srcset: "/press/press-rome-city-960.webp 960w, /press/press-rome-city-1440.webp 1440w",
    src: "/press/press-rome-city-1440.webp",
    width: 1440,
    height: 810,
    scrimForGold: 0.65,
  },
];

/** The frame to paint first. */
export const HERO: PressPlate = PRESS_PLATES[0];
