import * as THREE from 'three';

/**
 * Part-identity view for the soldier material.
 *
 * `engineMaterial.ts` already carries one of these for the siege engines, and it earned its
 * keep: a flat colour per part id is the only instrument that separates *missing* from
 * *hidden*. Five rounds of written critique on the scorpio could not settle whether the
 * trigger existed, because a small dark object inside a dark frame looks exactly like an
 * absent one. Painted magenta it took one frame.
 *
 * The soldier had no equivalent, and the same ambiguity applies twice over — a helmet the
 * shader has collapsed to a point (its kit bit is clear) and a helmet drawn inside the skull
 * are indistinguishable in a lit frame.
 *
 * The soldier material's own `onBeforeCompile` is set by `makeSoldierMaterial`, which this
 * file must not change. So it *chains*: capture the existing hook, call it, then inject on
 * top of what it produced. The material stays a `MeshStandardMaterial` patched through
 * `onBeforeCompile`; there is no second material and no `ShaderMaterial` anywhere.
 *
 * `aPieceTint.x` is the piece id, already declared as an attribute by the skinner's own
 * preamble, so the vertex side is one varying assignment.
 */

/**
 * Distinct-hue palette for 48 piece ids, generated by the golden-ratio hue walk rather than
 * hand-picked. Hand-picking 36 colours produces neighbours you cannot tell apart; a
 * φ-spaced hue sequence is the standard low-discrepancy answer and guarantees adjacent ids
 * — which are the ones most likely to touch on the mesh — are far apart on the wheel.
 */
export function pieceColour(id: number): THREE.Color {
  const h = (id * 0.6180339887 + 0.13) % 1;
  // Alternating value and saturation on top of the hue walk, so two pieces that happen to
  // land near each other in hue still differ in brightness.
  const s = 0.62 + 0.3 * ((id * 0.27) % 1);
  const v = 0.58 + 0.4 * ((id * 0.113 + 0.4) % 1);
  return new THREE.Color().setHSL(h, s, v * 0.5 + 0.12);
}

const FRAG = /* glsl */ `
if ( uViewerParts > 0.5 ) {
  vec3 rgb;
  // Flat colour alone loses all form — two overlapping pieces of the same hue merge into one
  // blob, which is the failure mode this view exists to avoid. A wrapped N.L keeps the
  // silhouette legible while staying far from anything that could be mistaken for shading.
  float lam = 0.62 + 0.38 * clamp( dot( normalize( normal ), normalize( vec3( 0.42, 0.78, 0.46 ) ) ), -1.0, 1.0 );

  if ( uViewerParts < 1.5 ) {
    // 1 — piece id.
    rgb = viewerHue( vViewerPiece );
  } else if ( uViewerParts < 2.5 ) {
    // 2 — primary bone id. Shows how the mesh is partitioned across the skeleton, which is
    // where a limb that comes apart in a pose was always going to come apart.
    rgb = viewerHue( vViewerBone );
  } else {
    // 3 — second-influence weight. Black is one bone, hot is a 50/50 blend. Every joint that
    // deforms rather than hinging must show a band here; a knee that is flat black is a knee
    // that will crease like cardboard, and no amount of staring at a lit render shows it.
    float w = clamp( vViewerWeight * 2.0, 0.0, 1.0 );
    rgb = mix( vec3( 0.04, 0.04, 0.09 ), vec3( 1.0, 0.86, 0.2 ), w );
    rgb = mix( rgb, vec3( 0.95, 0.25, 0.1 ), clamp( ( w - 0.5 ) * 2.0, 0.0, 1.0 ) );
    lam = 0.75 + 0.25 * lam;
  }
  gl_FragColor = vec4( rgb * lam, 1.0 );
}
`;

/**
 * φ-spaced hue for an integer id, in GLSL. Same walk as `pieceColour` on the CPU so the
 * swatches in the piece list are the colours on the model.
 */
const HUE = /* glsl */ `
vec3 viewerHue( float id ) {
  float h = fract( id * 0.6180339887 + 0.13 );
  float s = 0.62 + 0.3 * fract( id * 0.27 );
  float v = 0.58 + 0.4 * fract( id * 0.113 + 0.4 );
  vec3 rgb = clamp( abs( mod( h * 6.0 + vec3( 0.0, 4.0, 2.0 ), 6.0 ) - 3.0 ) - 1.0, 0.0, 1.0 );
  return v * mix( vec3( 1.0 ), rgb, s );
}
`;

/**
 * The switch, shared by every material this module patches so one write flips all of them.
 * 0 off, 1 piece ids, 2 bone ids, 3 skin weights.
 */
const uniform = { value: 0 };

const VARYINGS = 'varying float vViewerPiece;\nvarying float vViewerBone;\nvarying float vViewerWeight;\n';

/**
 * Chain a part-identity pass onto an already-patched soldier material.
 *
 * Only the colour material is worth patching: the depth and distance variants have no
 * fragment stage of ours and a diagnostic must never alter the shadow a model casts, or you
 * would be reading a different silhouette from the one the game draws.
 */
export function chainPartsDebug(material: THREE.MeshStandardMaterial, tag: string): void {
  const inner = material.onBeforeCompile.bind(material);
  const innerKey = material.customProgramCacheKey.bind(material);

  material.onBeforeCompile = (shader, renderer): void => {
    inner(shader, renderer);
    shader.uniforms.uViewerParts = uniform;

    // `#include <project_vertex>` survives the skinner's own rewrites — it only replaces
    // `beginnormal_vertex` and `begin_vertex` — so it is a stable anchor to hang the varyings
    // on, and it runs after `transformed` is final. `aPieceTint` and `aSkin` are both already
    // declared by the skinner's own preamble.
    shader.vertexShader = `${VARYINGS}${shader.vertexShader}`.replace(
      '#include <project_vertex>',
      'vViewerPiece = aPieceTint.x;\nvViewerBone = aSkin.x;\nvViewerWeight = aSkin.w;\n#include <project_vertex>'
    );

    // Last in the fragment shader, after dithering, so nothing downstream — tone mapping,
    // colour space conversion, fog — touches the diagnostic. Same placement the engine
    // material uses, and for the same reason: a part colour you have to mentally invert an
    // AgX curve out of is not a part colour.
    shader.fragmentShader = `${VARYINGS}uniform float uViewerParts;\n${HUE}\n${shader.fragmentShader}`
      .replace('#include <dithering_fragment>', `#include <dithering_fragment>\n${FRAG}`);
  };

  // The chained source differs from the unchained source, so it needs its own program.
  material.customProgramCacheKey = () => `${innerKey()}-viewer-parts-${tag}`;
}

/** 0 off · 1 piece ids · 2 bone ids · 3 skin weights. */
export function setPartsDebug(mode: number): void {
  uniform.value = mode;
}
